// Copyright (c) 2018-2026 by Jürgen Moßgraber (www.mossgrabers.de)
// Licensed under LGPLv3 - http://www.gnu.org/licenses/lgpl-3.0.txt

///////////////////////////////////////////////////////////////////
// Windows

#ifdef _WIN32
#define DISABLE_WARNING_PUSH           __pragma(warning( push ))
#define DISABLE_WARNING_POP            __pragma(warning( pop )) 
#define DISABLE_WARNING(warningNumber) __pragma(warning( disable : warningNumber ))

#define DISABLE_WARNING_BUFFER_OVERFLOW           DISABLE_WARNING(6386)
#define DISABLE_WARNING_MARK_AS_NOT_NULL          DISABLE_WARNING(26429)
#define DISABLE_WARNING_DONT_USE_NEW              DISABLE_WARNING(26409)
#define DISABLE_WARNING_NO_REF_TO_UNIQUE_PTR      DISABLE_WARNING(26411)
#define DISABLE_WARNING_PREFER_LOCAL_OBJECTS      DISABLE_WARNING(26414)
#define DISABLE_WARNING_USE_GSL_AT                DISABLE_WARNING(26446)
#define DISABLE_WARNING_CAN_THROW                 DISABLE_WARNING(26447)
#define DISABLE_WARNING_CAN_BE_CONST		      DISABLE_WARNING(26461)
#define DISABLE_WARNING_IDENTICAL_SOURCE_DEST     DISABLE_WARNING(26473)
#define DISABLE_WARNING_NO_POINTER_ARITHMETIC     DISABLE_WARNING(26481)
#define DISABLE_WARNING_ACCESS_ARRAYS_WITH_CONST  DISABLE_WARNING(26482)
#define DISABLE_WARNING_ARRAY_POINTER_DECAY       DISABLE_WARNING(26485)
#define DISABLE_WARNING_DANGLING_POINTER          DISABLE_WARNING(26486)
#define DISABLE_WARNING_DEREF_INVALID_POINTER     DISABLE_WARNING(26489)
#define DISABLE_WARNING_REINTERPRET_CAST          DISABLE_WARNING(26490)
#define DISABLE_WARNING_NO_STATIC_DOWNCAST        DISABLE_WARNING(26491)
#define DISABLE_WARNING_NO_C_STYLE_CONVERSION     DISABLE_WARNING(26493)

///////////////////////////////////////////////////////////////////
// Linux

#elif defined(__GNUC__) || defined(__clang__)
#define DO_PRAGMA(X) _Pragma(#X)
#define DISABLE_WARNING_PUSH           DO_PRAGMA(GCC diagnostic push)
#define DISABLE_WARNING_POP            DO_PRAGMA(GCC diagnostic pop) 
#define DISABLE_WARNING(warningName)   DO_PRAGMA(GCC diagnostic ignored #warningName)

#define DISABLE_WARNING_BUFFER_OVERFLOW
#define DISABLE_WARNING_MARK_AS_NOT_NULL
#define DISABLE_WARNING_DONT_USE_NEW
#define DISABLE_WARNING_NO_REF_TO_UNIQUE_PTR
#define DISABLE_WARNING_PREFER_LOCAL_OBJECTS
#define DISABLE_WARNING_USE_GSL_AT
#define DISABLE_WARNING_CAN_THROW
#define DISABLE_WARNING_CAN_BE_CONST
#define DISABLE_WARNING_IDENTICAL_SOURCE_DEST
#define DISABLE_WARNING_NO_POINTER_ARITHMETIC
#define DISABLE_WARNING_ACCESS_ARRAYS_WITH_CONST
#define DISABLE_WARNING_ARRAY_POINTER_DECAY
#define DISABLE_WARNING_DANGLING_POINTER
#define DISABLE_WARNING_DEREF_INVALID_POINTER
#define DISABLE_WARNING_REINTERPRET_CAST
#define DISABLE_WARNING_NO_STATIC_DOWNCAST
#define DISABLE_WARNING_NO_C_STYLE_CONVERSION

///////////////////////////////////////////////////////////////////
// macOS

#else
#define DISABLE_WARNING_PUSH
#define DISABLE_WARNING_POP

#define DISABLE_WARNING_BUFFER_OVERFLOW
#define DISABLE_WARNING_MARK_AS_NOT_NULL
#define DISABLE_WARNING_DONT_USE_NEW
#define DISABLE_WARNING_NO_REF_TO_UNIQUE_PTR
#define DISABLE_WARNING_PREFER_LOCAL_OBJECTS
#define DISABLE_WARNING_USE_GSL_AT
#define DISABLE_WARNING_CAN_THROW
#define DISABLE_WARNING_CAN_BE_CONST
#define DISABLE_WARNING_IDENTICAL_SOURCE_DEST
#define DISABLE_WARNING_NO_POINTER_ARITHMETIC
#define DISABLE_WARNING_ACCESS_ARRAYS_WITH_CONST
#define DISABLE_WARNING_ARRAY_POINTER_DECAY
#define DISABLE_WARNING_DANGLING_POINTER
#define DISABLE_WARNING_DEREF_INVALID_POINTER
#define DISABLE_WARNING_REINTERPRET_CAST
#define DISABLE_WARNING_NO_STATIC_DOWNCAST
#define DISABLE_WARNING_NO_C_STYLE_CONVERSION

#endif
