/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_mossgrabers_reaper_MainApp */

#ifndef _Included_de_mossgrabers_reaper_MainApp
#define _Included_de_mossgrabers_reaper_MainApp
#ifdef __cplusplus
extern "C" {
#endif
#undef de_mossgrabers_reaper_MainApp_DEVICE_UPDATE_RATE
#define de_mossgrabers_reaper_MainApp_DEVICE_UPDATE_RATE 30L
/*
 * Class:     de_mossgrabers_reaper_MainApp
 * Method:    processNoArg
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_mossgrabers_reaper_MainApp_processNoArg
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     de_mossgrabers_reaper_MainApp
 * Method:    processStringArg
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_mossgrabers_reaper_MainApp_processStringArg
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     de_mossgrabers_reaper_MainApp
 * Method:    processStringArgs
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_mossgrabers_reaper_MainApp_processStringArgs
  (JNIEnv *, jobject, jstring, jstring, jobjectArray);

/*
 * Class:     de_mossgrabers_reaper_MainApp
 * Method:    processIntArg
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_de_mossgrabers_reaper_MainApp_processIntArg
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     de_mossgrabers_reaper_MainApp
 * Method:    processDoubleArg
 * Signature: (Ljava/lang/String;Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_de_mossgrabers_reaper_MainApp_processDoubleArg
  (JNIEnv *, jobject, jstring, jstring, jdouble);

/*
 * Class:     de_mossgrabers_reaper_MainApp
 * Method:    delayUpdates
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_mossgrabers_reaper_MainApp_delayUpdates
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_mossgrabers_reaper_MainApp
 * Method:    enableUpdates
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_de_mossgrabers_reaper_MainApp_enableUpdates
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     de_mossgrabers_reaper_MainApp
 * Method:    processMidiArg
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_de_mossgrabers_reaper_MainApp_processMidiArg
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     de_mossgrabers_reaper_MainApp
 * Method:    getMidiInputs
 * Signature: ()Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_de_mossgrabers_reaper_MainApp_getMidiInputs
  (JNIEnv *, jobject);

/*
 * Class:     de_mossgrabers_reaper_MainApp
 * Method:    getMidiOutputs
 * Signature: ()Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_de_mossgrabers_reaper_MainApp_getMidiOutputs
  (JNIEnv *, jobject);

/*
 * Class:     de_mossgrabers_reaper_MainApp
 * Method:    openMidiInput
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_de_mossgrabers_reaper_MainApp_openMidiInput
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_mossgrabers_reaper_MainApp
 * Method:    openMidiOutput
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_de_mossgrabers_reaper_MainApp_openMidiOutput
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_mossgrabers_reaper_MainApp
 * Method:    closeMidiInput
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_mossgrabers_reaper_MainApp_closeMidiInput
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_mossgrabers_reaper_MainApp
 * Method:    closeMidiOutput
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_mossgrabers_reaper_MainApp_closeMidiOutput
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_mossgrabers_reaper_MainApp
 * Method:    sendMidiData
 * Signature: (I[B)V
 */
JNIEXPORT void JNICALL Java_de_mossgrabers_reaper_MainApp_sendMidiData
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     de_mossgrabers_reaper_MainApp
 * Method:    setNoteInputFilters
 * Signature: (II[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_mossgrabers_reaper_MainApp_setNoteInputFilters
  (JNIEnv *, jobject, jint, jint, jobjectArray);

/*
 * Class:     de_mossgrabers_reaper_MainApp
 * Method:    setNoteInputKeyTranslationTable
 * Signature: (II[I)V
 */
JNIEXPORT void JNICALL Java_de_mossgrabers_reaper_MainApp_setNoteInputKeyTranslationTable
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     de_mossgrabers_reaper_MainApp
 * Method:    setNoteInputVelocityTranslationTable
 * Signature: (II[I)V
 */
JNIEXPORT void JNICALL Java_de_mossgrabers_reaper_MainApp_setNoteInputVelocityTranslationTable
  (JNIEnv *, jobject, jint, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
